title: (°〇°)ﾉ lUser
email: lucazanny@gmail.com
description: >-
  lUser's personal blog on random (and maybe) techincal stuff
baseurl: ""
url: "https://blog.luser.fr"
github_username:  lusergit

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
include:
  - _posts

theme_config:
  back_home_text: "../" # customize text for homepage link in post layout
  date_format: "%Y-%m" # customize how date is formatted in post list
  show_description: true # show blog description in home page
  lowercase_titles: true
